// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pabeda.Projem.DataAccess.Concrete.EntityFramework;

namespace Pabeda.Projem.DataAccess.Migrations
{
    [DbContext(typeof(ProjemContext))]
    [Migration("20191109051102_Pabeda.Projem.DataAccess.Concrete.EntityFramework.ProjemContext")]
    partial class PabedaProjemDataAccessConcreteEntityFrameworkProjemContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OkuduguOkulOkulId")
                        .HasColumnType("int");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.HasIndex("OkuduguOkulOkulId");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.Ogretmen", b =>
                {
                    b.Property<int>("OgretmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OkulId")
                        .HasColumnType("int");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgretmenId");

                    b.HasIndex("OkulId");

                    b.ToTable("Ogretmens");
                });

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.OgretmenOgrenci", b =>
                {
                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenOgrenciId")
                        .HasColumnType("int");

                    b.HasKey("OgretmenId", "OgrenciId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgretmenOgrencis");
                });

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.Okul", b =>
                {
                    b.Property<int>("OkulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OkulId");

                    b.ToTable("Okuls");
                });

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.Ogrenci", b =>
                {
                    b.HasOne("Pabeda.Projem.Entities.Concrete.Okul", "OkuduguOkul")
                        .WithMany()
                        .HasForeignKey("OkuduguOkulOkulId");
                });

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.Ogretmen", b =>
                {
                    b.HasOne("Pabeda.Projem.Entities.Concrete.Okul", null)
                        .WithMany("Ogretmens")
                        .HasForeignKey("OkulId");
                });

            modelBuilder.Entity("Pabeda.Projem.Entities.Concrete.OgretmenOgrenci", b =>
                {
                    b.HasOne("Pabeda.Projem.Entities.Concrete.Ogrenci", "Ogrenci")
                        .WithMany("OgretmenOgrencis")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pabeda.Projem.Entities.Concrete.Ogretmen", "Ogretmen")
                        .WithMany("OgretmenOgrencis")
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
